DROP TABLE MANAGEDB.PUBLIC.PRODUCT

UNDROP TABLE MANAGEDB.PUBLIC.PRODUCT

DROP SCHEMA MANAGEDB.PUBLIC.FILE_FORMAT

UNDROP TABLE MANAGEDB.PUBLIC.FILE_FORMAT

DROP DATABASE MANAGEDB

UNDROP DATABASE MANAGEDB
