// Data scientists
CREATE WAREHOUSE DS_WH
WITH WAREHOUSE_SIZE='SMALL'
WAREHOUSE_TYPE= 'STANDARD'
AUTO_SUSPEND=300
AUTO_RESUME=TRUE
MIN_CLUSTER_COUNT=1
MAX_CLUSTER_COUNT=1
SCALING_POLICY='STANDARD';


//CREATE ROLE AND GIVE AUTHORITY TO ROLES

CREATE ROLE DATA_SCIENTIST
GRANT USAGE ON WAREHOUSE DS_WH TO ROLE DATA_SCIENTIST;

//CREATE USER LOGIN PASSWORD FOR ROLES
CREATE USER DS1 PASSWORD ='DS1' LOGIN_NAME ='DS1' DEFAULT_ROLE='DATA_SCIENTIST'
DEFAULT_WAREHOUSE='DS_WH' MUST_CHANGE_PASSWORD=FALSE
CREATE USER DS2 PASSWORD ='DS2' LOGIN_NAME ='DS2' DEFAULT_ROLE='DATA_SCIENTIST'
DEFAULT_WAREHOUSE='DS_WH' MUST_CHANGE_PASSWORD=FALSE


//GRANT ROLE
GRANT ROLE DATA_SCIENTIST TO USER DS1
GRANT ROLE DATA_SCIENTIST TO USER DS2