// CREATES A EMPLOYEES TABLE 
DECOURSE.PUBLIC.EMPLOYEES
CREATE OR REPLACE TABLE DECOURSE.PUBLIC.employees(
id INT,
first_name STRING,
last_name STRING,
email STRING,
location STRING,
department STRING
);

// CREATES A FILE FORMAT
CREATE OR REPLACE FILE FORMAT manageDB.file_formats.csv_file_format
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
null_if=('NULL','null')
empty_field_as_null=TRUE;

// CREATES A STAGE FOR DATA INTEGRATION
CREATE OR REPLACE STAGE MANAGEDB.EXTERNAL_STAGE.snowpipe_stage
URL="s3://ecommerce-dimension/snowpipe/"
STORAGE_INTEGRATION=my_s3_integration
FILE_FORMAT=MANAGEDB.FILE_FORMATS.CSV_FILE_FORMAT

LIST @MANAGEDB.EXTERNAL_STAGE.snowpipe_stage
LIST @MANAGEDB.PIPES.employee_pipe

// CREATES A SCHEMA FOR PIPES
CREATE OR REPLACE SCHEMA MANAGEDB.PIPES


// CREATES A SNOWPIPE
CREATE OR REPLACE pipe MANAGEDB.PIPES.employee_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO DECOURSE.PUBLIC.employees
FROM @MANAGEDB.EXTERNAL_STAGE.snowpipe_stage

// DESCRIPTION OF PIPE
DESC PIPE MANAGEDB.PIPES.employee_pipe

// SELECT * THE DATA 
SELECT * FROM DECOURSE.PUBLIC.EMPLOYEES

// CHECK AFTER 30-40 SECONDS 