
DROP TABLE IF EXISTS DECOURSE.PUBLIC.AISLE
CREATE OR REPLACE TABLE DECOURSE.PUBLIC.product(
product_id INT ,
product_name STRING,
aisle_name INT,
department_id INT
);


DROP FILE FORMAT MANAGEDB.FILE_FORMATS.CSV_FILE
CREATE OR REPLACE FILE FORMAT MANAGEDB.FILE_FORMATS.CSV_FILE
type='csv'
field_delimiter=','
skip_header =1

DROP STAGE IF EXISTS MANAGEDB.EXTERNAL_STAGE.time_travel_stage

CREATE OR REPLACE STAGE MANAGEDB.EXTERNAL_STAGE.time_travel_stage
STORAGE_INTEGRATION=my_s3_integration
URL="s3://ecommerce-dimension/"
file_format=MANAGEDB.FILE_FORMATS.CSV_FILE_FORMAT


LIST @MANAGEDB.EXTERNAL_STAGE.time_travel_stage;

COPY INTO DECOURSE.PUBLIC.PRODUCT
FROM @MANAGEDB.EXTERNAL_STAGE.TIME_TRAVEL_STAGE
FILES =('products.csv');

select * from DECOURSE.PUBLIC.PRODUCT


//use case - update data by mistakes
UPDATE DECOURSE.PUBLIC.PRODUCT
SET product_name='All-Seasons salt';

TRUNCATE DECOURSE.PUBLIC.PRODUCT;

//time travel method 1 - get data 2 minutes back 
insert into DECOURSE.PUBLIC.PRODUCT FROM select * from DECOURSE.PUBLIC.PRODUCT AT (OFFSET => -60*18));

INSERT INTO DECOURSE.PUBLIC.PRODUCT 
SELECT * 
FROM DECOURSE.PUBLIC.PRODUCT AT (OFFSET => -60*30);




