//CREATE OR DROP TABLE PRODUCT 

DROP TABLE IF EXISTS MANAGEDB.PUBLIC.PRODUCT

CREATE OR REPLACE TABLE MANAGEDB.PUBLIC.product(
product_id INT ,
product_name STRING,
aisle_name INT,
department_id INT
);

---

//CREATE  OR DROP SCHEMA , FILE FORMAT PRODUCT 

CREATE OR REPLACE SCHEMA MANAGEDB.file_formats

DROP FILE FORMAT MANAGEDB.FILE_FORMATS.CSV_FILE

CREATE OR REPLACE FILE FORMAT MANAGEDB.FILE_FORMATS.CSV_FILE
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'; 

---
//CREATE OR DROP STAGE time_travel_stage 
DROP STAGE IF EXISTS MANAGEDB.EXTERNAL_STAGE.time_travel_stage

CREATE OR REPLACE SCHEMA MANAGEDB.EXTERNAL_STAGE

CREATE OR REPLACE STAGE MANAGEDB.EXTERNAL_STAGE.time_travel_stage
STORAGE_INTEGRATION=my_s3_integration
URL="s3://ecommerce-dimension/"
file_format=MANAGEDB.FILE_FORMATS.CSV_FILE

LIST @MANAGEDB.EXTERNAL_STAGE.time_travel_stage;
---

//CREATE OR DROP OR DESC STORAGE INTEGRATION 

CREATE OR REPLACE STORAGE INTEGRATION my_s3_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://ecommerce-dimension')
    STORAGE_AWS_ROLE_ARN='arn:aws:iam::527552778365:role/snowflake_s3_connection'
    

DROP INTEGRATION my_s3_integration  
DESC INTEGRATION my_s3_integration;

---

//COPY DATA FROM AWS TO PRODUCT TABLE THROUGH STAGE
COPY INTO MANAGEDB.PUBLIC.PRODUCT
FROM @MANAGEDB.EXTERNAL_STAGE.TIME_TRAVEL_STAGE
FILES =('products.csv');

---

select * from MANAGEDB.PUBLIC.PRODUCT

//use case - update data by mistakes
UPDATE MANAGEDB.PUBLIC.PRODUCT
SET product_name='All-Seasons salt';


//time travel method 1 - get data 2 minutes back 
INSERT INTO MANAGEDB.PUBLIC.PRODUCT FROM SELECT * FROM MANAGEDB.PUBLIC.PRODUCT AT (OFFSET => -60*5));


//time travel method 2 - query time travel
//CREATE NEW TABLE 
CREATE OR REPLACE TABLE MANAGEDB.PUBLIC.PRODUCT_1 AS
SELECT * FROM MANAGEDB.PUBLIC.PRODUCT BEFORE (STATEMENT => '01c1f7d8-3202-459f-0000-00138092666d');

// clear main table 
TRUNCATE MANAGEDB.PUBLIC.PRODUCT;

// add new table from new table that contain data that before update
INSERT INTO MANAGEDB.PUBLIC.PRODUCT
SELECT * FROM MANAGEDB.PUBLIC.PRODUCT_1;

select * from MANAGEDB.PUBLIC.PRODUCT